// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cetjgphxdxidzjcmxfsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNldGpncGh4ZHhpZHpqY214ZnN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjYyMzksImV4cCI6MjA3MzM0MjIzOX0.wVLuoy1QismcVa16qvGi5qWtLVS166kAmQcKmwVNWDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});