// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkbjaqvouolimvmouulk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrYmphcXZvdW9saW12bW91dWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDE4NDMsImV4cCI6MjA3Mzc3Nzg0M30.hGufYnG-dNqfkUdkmD8n9comCD0vyxQDwZopihs8obY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});